name: Pre-deploy Workflow
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Clean Installation of Dependencies
        run: pnpm install --frozen-lockfile
      - name: ESLint
        run: pnpm eslint .
      - name: Format Code
        run: pnpm prettier . --write
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
    env:
      GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }}
